---
title: Khái niệm cơ bản
author: Duc Nguyen
date: '2022-07-09'
slug: khai-niem-co-ban
categories:
  - xác suất thống kê
tags:
  - thuật ngữ
subtitle: ''
summary: ''
authors: []
lastmod: '2022-07-09T22:04:46+07:00'
featured: no
output:
  blogdown::html_page:
    toc: yes
bibliography: D:/GITHUB/v5/zoterobib/xacsuat.bib
link-citations: yes
nocite: |
  @R-bookdown
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

## Nhập môn [xác suất] và [thống kê]

Có một số việc quan trọng cần làm rõ khi tìm hiểu về xác suất thống kê. 

Đầu tiên, thuật ngữ *chỉ số thống kê* (tiếng anh là *a statistic*) là một con số được tính toán từ một *mẫu* (sample) của một dữ liệu nào đó.

Thứ hai là, một *biến* (variable) là kết quả đầu ra (outcome) từ một thí nghiệm.

Logic ở đây là dựa trên khái niệm tính tất định, tất yếu xảy ra, có thể tính toán được nếu chúng ta biết được điều kiện biên ban đầu của bài toán, biết được phân phối xác suất, khả năng xảy ra sự kiện nào đó thì chúng ta sẽ dự đoán được kết quả xảy ra **dao động trong một khoảng** nào đó. Gọi là *deterministic system* hay là *hệ tất định* (không còn yếu tố ngẫu nhiên, không phải bất định).

> In mathematics, computer science and physics, [a deterministic system][1] is a system in which no randomness is involved in the development of future states of the system.[1] A deterministic model will thus always produce the same output from a given starting condition or initial state.

Do vậy, 

> We want to emphasize a couple of important points here. First, a statistic (singular) is a number computed from a sample of data. We use statistics to infer information about a population. Second, a random variable is an outcome from an experiment. Deterministic processes, such as computing means or variances, applied to random variables, produce additional random variables which have their own distributions. It's important to keep straight which distributions you're talking about.

Finally, there are two broad flavors of inference. The first is frequency, which uses "long run proportion of times an event occurs in independent, identically distributed repetitions." The second is Bayesian in which the probability estimate for a hypothesis is updated as additional evidence is acquired. Both flavors require an understanding of probability [@swirl2020].

## Probability

Here we'll review basic ideas of probability, the study of quantifying the likelihood of particular events occurring. Note the similarity between the words probability and probably. Every time you use the latter word you're implying that an event is more likely than not to occur.

The first step in understanding probability is to see if you understand what  outcomes of an experiment are possible. For instance, if you were rolling a single, fair die once, how many outcomes are possible?
 
The answer is 6 types of outcome from 1 to 6 point per dice's plane.
 
The probability of a particular outcome of an experiment is the ratio of the number of ways that outcome can occur to all possible outcomes of the experiment. Since there are 6 possible outcomes to the experiment of rolling a die, and we assume the die is fair, each outcome is equally likely. So what is the probability of rolling a 2? *Xác suất để tung ra mặt có 2 điểm là $1/6$*

What is the probability of rolling an even number? Xác xuất để tung ra số chẵn (2, 4, 6) là $1/2$. 

Since the probability of a particular outcome or event E is the ratio of ways that E could occur to the number of all possible outcomes or events, the probability of $E$, denoted $P(E)$, is **always** between 0 and 1. <span style="color:blue">**Impossible events**</span> have a probability of 0 (since they can't occur) and events that are <span style="color:blue">**certain to occur**</span>  have a probability of 1.

If you're doing an experiment with <span style="color:red">***n***</span> possible outcomes, say e~1~, e~2~, ..., e~n~, then the sum of the probabilities of all the outcomes is 1. If all the outcomes are equally likely, as in the case of a fair die, then the probability of each is $1/n$.

If $A$ and $B$ are two **independent** events then the <mark>probability</mark> of them **both occurring** is the product of the probabilities, $P(A \& B) = P(A) \times P(B)$.

> Suppose you rolled the fair die twice in succession. What is the probability of rolling two 4's? The probability of rolling the first 4 is $1/6$. The second roll of the dice doesn't depend on the outcome of the first, so that also has a probability of $1/6$. The probability of both events occurring is $1/6 \times 1/6$. This makes intuitive sense since the probability of 2 such events occurring has to be smaller than the probability of only 1 event. Xác suất để gieo xúc sắc liên tiếp hai lần mà đều xuất hiện mặt có 4 điểm là $1/6 \times 1/6 = 1/36$.

> Suppose you rolled the fair die twice. What is the probability of rolling the same number two times in a row? Since we don't care what the outcome of the first roll is, its probability is $1$. The second roll of the dice has to match the outcome of the first, so that has a probability of $1/6$. The probability of both events occurring is $1 \times 1/6$.

Now consider the experiment of rolling 2 dice, one red and one green. Assume the dice are fair and not loaded. How many distinct outcomes are possible? Each of the dice has 6 ways to land, and their outcomes are independent of each other. Each way the red die lands can be paired with each way the green die lands. For instance, a "1" on the red dice can occur independently of any of the 6 outcomes of the green dice. So the answer is 36 distinct outcomes.

If an event E can occur in more than one way and these ways are disjoint (mutually exclusive) then P(E) is the sum of the probabilities of each of the ways in which it can occur.

Rolling these two dice, what's the probability of rolling a 10? Since the highest possible dice roll is a '6', the only combinations which give '10' are 4+6 and 5+5. The first occurs in two ways - red dice gets '4' and green gets '6' OR red gets '6' and green gets '4'. So 3/36 is the answer.

What sum is the most likely when rolling these two dice? The choice of '1' is impossible rolling two dice, and '2' and '12' each occur in only one possible way (snake-eyes and double 6's, respectively), so '7' and '9' are the only reasonable choices. To roll '7' you can use any number from '1' to '6', while '9' can only use outcomes of '3' and above. 7 is the correct answer.

The probability of at least one of two events, A and B, occurring is the sum of their individual probabilities minus the probability of their intersection. P(A U B) = P(A) + P(B) - P(A&B).

It's easy to see why this is. Calculating P(A) and P(B) counts outcomes that are in both A and B twice, so they're overcounted. The probability of the intersection of the two events, denoted as A&B, must be subtracted from the sum.

Back to rolling two dice. Which expression represents the probability of rolling an even number or a number greater than 8? The probability of rolling an even number is 1/2 or 18/36. There are 10 ways of rolling a number greater than '8' - 4 ways for rolling '9', 3 for '10', 2 for '11' and 1 for '12'. How big is the intersection between rolling an even number and those greater than '8'? (18+10-4)/36 is the answer.

It follows that if A and B are disjoint or mutually exclusive, i.e. only one of them can occur, then P(A U B) = P(A)+P(B).

Which of the following expressions represents the probability of rolling a number greater than 10? The only outcomes greater than 10 are 11 and 12 which are mutually exclusive. The first, 11, can occur in two ways, and the second, 12, can occur only with a roll of double 6's. (2+1)/36.

Use the answer to the previous question and the fact that the sum of all outcomes must sum to 1 to determine the probability of rolling a number less than or equal to 10. Hint: Subtract the previous answer from 1. 11/12.

## Now we'll apply the concepts of probability to playing cards.

A deck of cards is a set of 52 cards, 4 suits of 13 cards each. There are two red suits, diamonds and hearts, and two black suits, spades and clubs. Each of the 13 cards in a suit has a value - an ace which is sometimes thought of as 1, a number from 2 to 10, and 3 face cards, king, queen, and jack. We've created a deck in R for you. Type 'deck' to see it now.

```
deck
      spades      hearts      diamonds      clubs     
 [1,] "A:spades"  "A:hearts"  "A:diamonds"  "A:clubs" 
 [2,] "2:spades"  "2:hearts"  "2:diamonds"  "2:clubs" 
 [3,] "3:spades"  "3:hearts"  "3:diamonds"  "3:clubs" 
 [4,] "4:spades"  "4:hearts"  "4:diamonds"  "4:clubs" 
 [5,] "5:spades"  "5:hearts"  "5:diamonds"  "5:clubs" 
 [6,] "6:spades"  "6:hearts"  "6:diamonds"  "6:clubs" 
 [7,] "7:spades"  "7:hearts"  "7:diamonds"  "7:clubs" 
 [8,] "8:spades"  "8:hearts"  "8:diamonds"  "8:clubs" 
 [9,] "9:spades"  "9:hearts"  "9:diamonds"  "9:clubs" 
[10,] "10:spades" "10:hearts" "10:diamonds" "10:clubs"
[11,] "J:spades"  "J:hearts"  "J:diamonds"  "J:clubs" 
[12,] "Q:spades"  "Q:hearts"  "Q:diamonds"  "Q:clubs" 
[13,] "K:spades"  "K:hearts"  "K:diamonds"  "K:clubs" 
```
When drawing a single card, how many outcomes are possible? 52.
What is the probability of drawing a jack? 4/52 (có 4 con jack).
If you're dealt a hand of 5 cards, what is the probability of getting all 5 of the same value?
There are only 4 different suits in a deck. 0 is the answer.

What is the probability of drawing a face card? There are 3 face cards in each of the 4 suits in the deck. 3/13

Suppose you draw a face card and don't replace it in the deck. What is the probability that when you draw a second card it also will be a face card? There are only 51 cards remaining in the deck, and of those, only 11 are face cards. 11/51.

Suppose you draw a face card and don't replace it in the deck. What is the probability that when you draw a second card it also will be a face card of the same suit? There are 2 face cards of the same suit left in the deck. 2/51.

## Tài liệu tham khảo

[1]: https://en.wikipedia.org/wiki/Deterministic_system/ 

